apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apex
spec:
  destination:
    name: smaug
    namespace: apex
  source:
    path: deploy/apex/overlays/prod
    repoURL: 'https://github.com/redhat-et/apex'
    targetRevision: HEAD
  project: apex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
